"""add commercial invoices

Revision ID: 66bc25c17066
Revises: e4bb2dca855f
Create Date: 2026-06-09 15:53:03.809522

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '66bc25c17066'
down_revision: str | Sequence[str] | None = 'e4bb2dca855f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_number_sequences',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('prefix', sa.String(length=16), server_default='INV', nullable=False),
    sa.Column('last_number', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('customers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('tax_id', sa.String(length=50), nullable=True),
    sa.Column('billing_address_line1', sa.String(length=255), nullable=False),
    sa.Column('billing_address_line2', sa.String(length=255), nullable=True),
    sa.Column('billing_city', sa.String(length=120), nullable=False),
    sa.Column('billing_state', sa.String(length=120), nullable=True),
    sa.Column('billing_postal_code', sa.String(length=20), nullable=True),
    sa.Column('billing_country', sa.String(length=2), server_default='US', nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('contracts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('contract_date', sa.Date(), nullable=False),
    sa.Column('currency_code', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('service_period_start', sa.Date(), nullable=True),
    sa.Column('service_period_end', sa.Date(), nullable=True),
    sa.Column('scope_description', sa.String(length=2000), nullable=True),
    sa.Column('agreed_rate', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('rate_unit', sa.String(length=40), nullable=True),
    sa.Column('payment_terms_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column(
        'default_tax_rate', sa.Numeric(precision=7, scale=4),
        server_default='0', nullable=False,
    ),
    sa.Column(
        'default_discount', sa.Numeric(precision=18, scale=4),
        server_default='0', nullable=False,
    ),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('next_period_start', sa.Date(), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'reference', name='uq_contracts_customer_reference'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_contracts_customer_id'), 'contracts', ['customer_id'], unique=False)
    op.create_table('issuer_profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('legal_name', sa.String(length=255), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=2), server_default='PY', nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('bank_address', sa.String(length=500), nullable=True),
    sa.Column('bank_country', sa.String(length=2), server_default='PY', nullable=False),
    sa.Column('swift_bic', sa.String(length=20), nullable=False),
    sa.Column('account_number', sa.String(length=64), nullable=True),
    sa.Column('iban', sa.String(length=64), nullable=True),
    sa.Column('intermediary_bank_name', sa.String(length=255), nullable=True),
    sa.Column('intermediary_swift_bic', sa.String(length=20), nullable=True),
    sa.Column('intermediary_account_number', sa.String(length=64), nullable=True),
    sa.Column('intermediary_bank_country', sa.String(length=2), server_default='US', nullable=True),
    sa.Column('receiving_account_id', sa.BigInteger(), nullable=True),
    sa.Column(
        'bank_receiving_fee', sa.Numeric(precision=18, scale=4),
        server_default='44', nullable=False,
    ),
    sa.Column('default_income_category_id', sa.BigInteger(), nullable=True),
    sa.Column('wire_reference_instructions', sa.String(length=1000), nullable=True),
    sa.Column('default_payment_terms_days', sa.Integer(), server_default='30', nullable=False),
    sa.Column('tax_status_note', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['default_income_category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiving_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_table('invoices',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('number', sa.String(length=40), nullable=True),
    sa.Column(
        'status',
        sa.Enum(
            'draft', 'issued', 'sent', 'paid', 'void',
            name='invoicestatus', native_enum=False, length=50,
        ),
        server_default='draft', nullable=False,
    ),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('contract_id', sa.BigInteger(), nullable=True),
    sa.Column('currency_code', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('receivable_id', sa.BigInteger(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('service_period_start', sa.Date(), nullable=True),
    sa.Column('service_period_end', sa.Date(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column(
        'discount_total', sa.Numeric(precision=18, scale=4),
        server_default='0', nullable=False,
    ),
    sa.Column('tax_total', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column(
        'bank_fee_amount', sa.Numeric(precision=18, scale=4),
        server_default='44', nullable=False,
    ),
    sa.Column('issuer_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('customer_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('po_number', sa.String(length=60), nullable=True),
    sa.Column('terms', sa.String(length=2000), nullable=True),
    sa.Column('notes', sa.String(length=2000), nullable=True),
    sa.Column('void_reason', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_sha256', sa.String(length=64), nullable=True),
    sa.Column('pdf_generated_at', sa.DateTime(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('voided_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['currency_code'], ['currencies.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['receivable_id'], ['receivables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number', name='uq_invoices_number'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(op.f('ix_invoices_contract_id'), 'invoices', ['contract_id'], unique=False)
    op.create_index(
        op.f('ix_invoices_created_by_user_id'), 'invoices',
        ['created_by_user_id'], unique=False,
    )
    op.create_index(op.f('ix_invoices_customer_id'), 'invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_invoices_due_date'), 'invoices', ['due_date'], unique=False)
    op.create_index(op.f('ix_invoices_receivable_id'), 'invoices', ['receivable_id'], unique=False)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_index('ix_invoices_status_due_date', 'invoices', ['status', 'due_date'], unique=False)
    op.create_table('invoice_line_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('invoice_id', sa.BigInteger(), nullable=False),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=4), server_default='1', nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=7, scale=4), server_default='0', nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('line_tax', sa.Numeric(precision=18, scale=4), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_unicode_ci'
    )
    op.create_index(
        op.f('ix_invoice_line_items_invoice_id'), 'invoice_line_items',
        ['invoice_id'], unique=False,
    )

    # Seed the single-row invoice number counter so the first allocated
    # invoice is INV-000101 (last_number=100 -> +1 -> 101 -> "INV-000101").
    op.execute(
        "INSERT INTO invoice_number_sequences (id, prefix, last_number) "
        "VALUES (1, 'INV', 100)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema: drop the 6 new tables in reverse dependency order."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoice_line_items_invoice_id'), table_name='invoice_line_items')
    op.drop_table('invoice_line_items')
    op.drop_index('ix_invoices_status_due_date', table_name='invoices')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_receivable_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_due_date'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_customer_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_created_by_user_id'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_contract_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_table('issuer_profiles')
    op.drop_index(op.f('ix_contracts_customer_id'), table_name='contracts')
    op.drop_table('contracts')
    op.drop_table('customers')
    op.drop_table('invoice_number_sequences')
    # ### end Alembic commands ###
