from datetime import datetime

from pydantic import BaseModel, EmailStr, Field

from app.models.enums import UserRole


class UserCreate(BaseModel):
    email: EmailStr = Field(
        ...,
        description="Email of the new user. Must be unique — server returns 409 on conflict.",
        examples=["new.user@example.com"],
    )
    name: str = Field(
        ...,
        min_length=1,
        max_length=255,
        description="Display name of the new user.",
        examples=["Maria Souza"],
    )
    role: UserRole = Field(
        UserRole.member,
        description="Role to assign on creation. Defaults to `member`.",
        examples=["member"],
    )


class UserUpdate(BaseModel):
    name: str | None = Field(
        default=None,
        min_length=1,
        max_length=255,
        description="New display name. Omit to preserve.",
        examples=["Maria S. Souza"],
    )
    role: UserRole | None = Field(
        None,
        description="New role. Omit to preserve.",
        examples=["admin"],
    )
    is_active: bool | None = Field(
        None,
        description="Toggle active flag. Setting `false` deactivates without deleting.",
        examples=[True],
    )


class UserListItem(BaseModel):
    id: int = Field(..., description="Server-assigned user id.", examples=[1])
    email: EmailStr = Field(..., description="User email (immutable post-creation).", examples=["user@example.com"])
    name: str = Field(..., description="Display name.", examples=["Caio Norder"])
    role: UserRole = Field(..., description="Role: `admin`, `member` or `viewer`.", examples=["admin"])
    is_active: bool = Field(..., description="False for soft-deleted/deactivated users.", examples=[True])
    created_at: datetime = Field(..., description="UTC timestamp of account creation.")

    model_config = {"from_attributes": True}


class UserCreatedResponse(UserListItem):
    temporary_password: str = Field(
        ...,
        description=(
            "Plaintext temporary password generated by the server. Returned **only** in the "
            "response to `POST /users` — it cannot be retrieved later. Hand it to the user "
            "out-of-band; they should change it on first login via "
            "`POST /users/me/change-password`."
        ),
        examples=["X4kZ-q7Pn-A2hd"],
    )


class PasswordResetResponse(BaseModel):
    temporary_password: str = Field(
        ...,
        description=(
            "New plaintext temporary password. Returned **only** in the response to "
            "`POST /users/{id}/reset-password`."
        ),
        examples=["X4kZ-q7Pn-A2hd"],
    )


class ChangePasswordRequest(BaseModel):
    current_password: str = Field(
        ...,
        description="The caller's current password — required as proof of possession.",
        examples=["old-passw0rd"],
    )
    new_password: str = Field(
        ...,
        min_length=8,
        max_length=128,
        description=(
            "Desired new password (8-128 chars). Server-side strength rules may reject "
            "trivially weak values with a 400."
        ),
        examples=["n3w-str0ng-passw0rd"],
    )
